name: build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get Next Tag
      id: tag_version
      uses: SOLIDSoftworks/semver-tags@1.0.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        tag-prefix: 'v'
        dry-run: true
    - name: Update Tbac Version
      env:
       TBAC_VERSION: ${{ steps.tag_version.outputs.semantic-version }}
      run: |
        version=$(cat cmd/root.go |grep version|tr -d \"|awk -F ' ' '{print $NF}')
        echo "Printing versions" > temp.txt
        echo "Go version: $version" >> temp.txt
        echo "Next Tag version: $TBAC_VERSION" >> temp.txt
        cat temp.txt
        sed -i 's/${{ versions }}/${{ TBAC_VERSION }}/' cmd/root.go
        version_1=$(cat cmd/root.go |grep version|tr -d \"|awk -F ' ' '{print $NF}')
        echo "printing again" >> temp.txt
        echo "Go version: $version_1" >> temp.txt
        cat temp.txt
        git status
        git diff cmd/root.go
  
        
    - name: Get dependencies
      run: |
        version_2=$(cat cmd/root.go |grep version|tr -d \"|awk -F ' ' '{print $NF}')
        echo "printing final" >> temp.txt
        echo "Go version: $version_2" >> temp.txt
        cat temp.txt
