name: build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get Next Tag
      id: tag_version
      uses: SOLIDSoftworks/semver-tags@1.0.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        tag-prefix: 'v'
        dry-run: true
    - name: Update Tbac Version
      env:
       TBAC_VERSION: ${{ steps.tag_version.outputs.semantic-version }}
      run: |
        cat cmd/root.go > cmd/temp.go
        version=$(cat cmd/temp.go |grep version|tr -d \"|awk -F ' ' '{print $NF}')
        echo "Printing versions" > temp.txt
        echo $version >> temp.txt
        echo $TBAC_VERSION >> temp.txt
        cat temp.txt
        sed -i 's/$version/$TBAC_VERSION/' cmd/temp.go
        cat cmd/temp.go
        version_1=$(cat cmd/temp.go |grep version|tr -d \"|awk -F ' ' '{print $NF}')
        echo "printing again" >> temp.txt
        echo $version_1 >> temp.txt
        cat temp.txt
        cat cmd/temp.go
        rm -rf cmd/root.go
        ls -ltr
        cat cmd/temp.go > cmd/root.go
        cat cmd/root.go
        pwd
        ls -ltr
    - name: Get dependencies
      run: |
        cat cmd/root.go
        version_2=$(cat cmd/root.go |grep version|tr -d \"|awk -F ' ' '{print $NF}')
        echo "printing final" >> temp.txt
        echo $version_2 >> temp.txt
        cat temp.txt
